language: c

sudo: false

before_install:
    - source <(curl -SLs https://raw.githubusercontent.com/fede2cr/travis-ci-arduino/master/install.sh)

install:
    - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/khairulhasanmd/USBino/master/package_khairulhasanmd_usbino_index.json" --save-prefs
    - arduino --install-boards USBino:avr
    - export BLINK=$(find $HOME/arduino_ide -type f -name 'Blink.ino' -print -quit)
    - echo "Compiling \"$BLINK\""

script:
    - arduino --verify --board USBino:avr:sanguino:cpu=atmega32 $BLINK
